# app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
  namespace: argocd
spec:
  destination:
    namespace: rails-app
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:vinaysunhare/Dockerized-Rails-app-with-PostgreSQL.git
    targetRevision: HEAD
    path: .  # root of the repo or specify folder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
