# rails-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rails-service
  namespace: rails-app
spec:
  selector:
    app: rails-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000         # Kubernetes service port (external interface)
      targetPort: 3000   # Port inside the container where Rails app runs
      nodePort: 30080    # NodePort (used in http://192.168.49.2:30080)
