apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  params:
    - name: git-url
    - name: image-url
    - name: dockerfile
      default: Dockerfile
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-and-push
      taskRef:
        name: build-and-push
      runAfter:
        - clone-source
      params:
        - name: IMAGE
          value: $(params.image-url)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: .
      workspaces:
        - name: source
          workspace: shared-workspace
