apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-run-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: git-url
      value: https://github.com/vinaysunhare/Dockerized-Rails-app-with-PostgreSQL.git
    - name: image-url
      value: docker.io/vinaysunhare/railsapp:latest
    - name: DOCKERFILE
      value: Dockerfile
    - name: CONTEXT
      value: .
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-workspace-pvc
  serviceAccountName: pipeline-sa  # ✅ Use dedicated service account
  podTemplate:
    imagePullSecrets:
      - name: regcred