apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-run-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: git-url
      value: https://github.com/vinaysunhare/Dockerized-Rails-app-with-PostgreSQL.git
    - name: image-url
      value: docker.io/vinaysunhare/railsapp:latest
    - name: DOCKERFILE
      value: k8s/Dockerfile       # ✅ Point to correct path
    - name: CONTEXT
      value: k8s                  # ✅ Build context is 'k8s' folder
  workspaces:
    - name: shared-workspace
      emptyDir: {}
  serviceAccountName: default
