apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  params:
    - name: git-url
    - name: image-url
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: deleteExisting
          value: "true"

    - name: build-and-push
      runAfter:
        - clone-source
      taskRef:
        name: build-and-push
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-url)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: $(workspaces.source.path)
