default: &default
  adapter: postgresql
  encoding: unicode
  host: db

development:
  <<: *default
  database: myapp_development
  username: vinaysunhare
  password: vinay123
  host: localhost

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>